"""Ring backdrop for the design-v2 screens without their own master (D43: profile, settings, deck, results): the
loading master's stadium (its extended plate, wings included) with the baked RAP BRAWL logo removed by LaMa, so the
live 3D fighter can stand in the middle of the ring. Run after v2_loading.py; then depth.py ring.

Usage: python3 tools/ui-extract/v2_ring.py  ->  public/assets/ui2/ring/plate_l|c|r.webp + src/ui/v2/art/ring.ts"""
import json
import os
import sys

import cv2
import numpy as np

sys.path.insert(0, os.path.dirname(__file__))
import uix  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'public', 'assets', 'ui2', 'loading')
OUT = os.path.join(ROOT, 'public', 'assets', 'ui2', 'ring')
DBG = os.path.join(ROOT, '.cache', 'ui2')
PLATE = {"l": [-400, 0, 404, 941], "c": [-4, 0, 1680, 941], "r": [1668, 0, 404, 941]}
X0 = -400
# the logo's silhouette in master px (mic, RAP, BRAWL, fist, belt) - traced on a grid crop, grown below
LOGO = [(555, 12), (700, 28), (990, 30), (1062, 36), (1114, 118), (1112, 188), (1128, 290), (1104, 332), (1082, 372), (1000, 424), (840, 448),
        (690, 428), (606, 400), (560, 398), (498, 362), (494, 300), (512, 200), (542, 166), (548, 88)]

os.makedirs(OUT, exist_ok=True)
os.makedirs(DBG, exist_ok=True)
W = 1672 + 2 * 400
wide = np.zeros((941, W, 3), np.uint8)
for k in ('l', 'r', 'c'):  # wings first, centre on top
    x, y, w, h = PLATE[k]
    t = cv2.imread(os.path.join(SRC, f'plate_{k}.webp'))
    wide[:, x - X0:x - X0 + w] = cv2.resize(t, (w, h), interpolation=cv2.INTER_AREA)
mask = np.zeros(wide.shape[:2], np.uint8)
cv2.fillPoly(mask, [np.array([(px - X0, py) for px, py in LOGO], np.int32)], 255)
mask = uix.dilate(mask, 10)
clean = uix.inpaint(wide, mask, max_side=1024, ctx=0.55, feather=8)
cv2.imwrite(os.path.join(DBG, 'ring_plate.png'), clean)
for k, (x, y, w, h) in PLATE.items():
    uix.save_rgba(os.path.join(OUT, f'plate_{k}.webp'), clean[:, x - X0:x - X0 + w], None, quality=86 if k == 'c' else 80)
ts = os.path.join(ROOT, 'src', 'ui', 'v2', 'art', 'ring.ts')
src = open(os.path.join(ROOT, 'src', 'ui', 'v2', 'art', 'loading.ts')).read()
lights = src[src.index('export const LOADING_LIGHTS'):].split('=', 1)[1].strip().rstrip(';')
# no glows where the logo was
lt = [l for l in json.loads(lights) if not (500 <= l[0] <= 1130 and l[1] <= 450)]
open(ts, 'w').write(
    '// GENERATED by tools/ui-extract/v2_ring.py - do not edit by hand (re-run the script instead).\n'
    '// The loading master\'s stadium without the logo (D43): backdrop of the v2 profile, settings, deck and results screens.\n\n'
    "export const RING_DIR = 'assets/ui2/ring/';\n"
    f'export const RING_PLATE = {json.dumps(PLATE)} as const;\n'
    'export const RING_ART = {} as const;\n'
    f'export const RING_LIGHTS: [number, number, number, [number, number, number]][] = {json.dumps(lt)};\n'
)
print('ring plate ->', OUT, 'lights', len(lt))
