"""Design v4 (D47): the PO's street master set (Frankfurt / Berlin, tools/ui-extract/ref/v4/*.png, git-ignored).

The masters (1599x900) are resampled to the 1672x941 reference grid of the v2 runtime (same aspect) by
`python3 tools/ui-extract/v4_screens.py prep <dir>`; everything else is the v2 pipeline (v2x.py): the PO's pixels are
the art, the plate is the master with only the changing parts removed (live numbers and names, third-party logos),
UI elements become sprites that lie on their own pixels (pressable, lit at runtime), wide phones see outpainted
wings. Nothing is drawn new.

Additions over v2x:
  shape 'frame'   element mask from the gold/neon frame around it: flood fill of the frame interior from `core`,
                  grown by the frame width (`ring`), convex hull - adjacent tiles whose frames touch separate cleanly
  ring sprites    `rings(screen, {name: (element box, core, ring px)})`: only the frame of a tile (selection states:
                  a blue frame moved onto another tile)
Output: public/assets/ui4/<screen>/, src/ui/v4/art/<screen>.ts
"""
from __future__ import annotations

import json
import os
import sys

import cv2
import numpy as np

sys.path.insert(0, os.path.dirname(__file__))
import uix  # noqa: E402
import v2x  # noqa: E402

v2x.REF_DIR = 'tools/ui-extract/ref/v4'
v2x.PUB = os.path.join(uix.ROOT, 'public/assets/ui4')
v2x.TS_DIR = os.path.join(uix.ROOT, 'src/ui/v4/art')
v2x.DBG = os.path.join(uix.ROOT, '.cache/ui4')
PUB = v2x.PUB
REF = os.path.join(uix.ROOT, v2x.REF_DIR)

# frame colours (OpenCV HSV, H 0..180): gold rims, blue neon, red neon
FRAME_HSV = {
    'gold': [((10, 90, 140), (36, 255, 255))],
    'blue': [((95, 80, 150), (130, 255, 255))],
    'red': [((0, 90, 140), (9, 255, 255)), ((170, 90, 140), (180, 255, 255))],
}


def frame_pixels(img, kinds=('gold', 'blue', 'red')):
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    m = np.zeros(img.shape[:2], np.uint8)
    for k in kinds:
        for lo, hi in FRAME_HSV[k]:
            m |= cv2.inRange(hsv, np.array(lo), np.array(hi))
    return m


def frame_mask(img, box, core, ring=12, kinds=('gold', 'blue', 'red'), seal=3, close=15):
    """Tile = interior flood-filled from `core` inside the frame (walls = frame-coloured pixels), grown by the frame
    width, convex hull, clipped to `box`."""
    H, W = img.shape[:2]
    x0, y0, x1, y1 = box
    walls = uix.dilate(frame_pixels(img[y0:y1, x0:x1], kinds), seal)
    # bridge short gaps in a frame line (a shadowed bevel corner) so the interior cannot leak out
    walls = cv2.morphologyEx(walls, cv2.MORPH_CLOSE, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (close, close)))
    inside = np.zeros((y1 - y0, x1 - x0), np.uint8)
    for cx0, cy0, cx1, cy1 in core:
        inside[cy0 - y0:cy1 - y0, cx0 - x0:cx1 - x0] = 255
    free = (walls == 0).astype(np.uint8)
    n, lab = cv2.connectedComponents(free)
    keep = np.zeros_like(inside)
    for i in np.unique(lab[inside > 0]):
        if i == 0:
            continue
        comp = (lab == i).astype(np.uint8) * 255
        touches = comp[0, :].any() or comp[-1, :].any() or comp[:, 0].any() or comp[:, -1].any()
        if touches:  # leaked out of the frame: only the core itself
            continue
        keep |= comp
    keep |= inside
    keep = uix.fill_holes(keep)
    grown = uix.dilate(keep, ring)
    cnts, _ = cv2.findContours(grown, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    out = np.zeros_like(grown)
    if cnts:
        cv2.fillPoly(out, [cv2.convexHull(np.vstack(cnts))], 255)
    full = np.zeros((H, W), np.uint8)
    full[y0:y1, x0:x1] = out
    return full


_orig_mask = v2x.element_mask


def element_mask(img, e):
    if e.get('shape') == 'frame':
        return frame_mask(img, e['box'], e.get('core', [e['box']]), ring=e.get('ring_w', 12), kinds=e.get('kinds', ('gold', 'blue', 'red')))
    return _orig_mask(img, e)


v2x.element_mask = element_mask


def write_ts(screen, sprites, texts, tiles, lights_, extra, size):
    os.makedirs(v2x.TS_DIR, exist_ok=True)
    name = v2x.ident(screen).upper()
    L = [f'// GENERATED by tools/ui-extract/v4_screens.py {screen} - do not edit by hand (re-run the script instead).',
         '// Boxes are [x, y, w, h] in reference px of the 1672x941 grid (the PO master resampled); files live in',
         '// public/assets/ui4/.', '',
         f"export const {name}_DIR = 'assets/ui4/{screen}/';",
         f'export const {name}_SIZE = {json.dumps(list(size))} as const;',
         f'export const {name}_PLATE = {json.dumps(tiles)} as const;',
         f'export const {name}_ART = {{']
    for k, v in sprites.items():
        L.append(f'  {json.dumps(k)}: {json.dumps(v)},')
    L.append('} as const;')
    L.append(f'export const {name}_TEXT = {{')
    for k, v in texts.items():
        L.append(f'  {json.dumps(k)}: {json.dumps(v)},')
    L.append('} as const;')
    L.append(f'export const {name}_LIGHTS: [number, number, number, [number, number, number]][] = {json.dumps(lights_)};')
    for k, v in extra.items():
        L.append(f'export const {name}_{k.upper()} = {json.dumps(v)} as const;')
    L.append('')
    with open(os.path.join(v2x.TS_DIR, f'{screen}.ts'), 'w') as f:
        f.write('\n'.join(L))


v2x.write_ts = write_ts


def load(screen):
    return uix.load(os.path.join(v2x.REF_DIR, f'{screen}.png'))


def save_part(screen, name, rgb, alpha, box, quality=92):
    """Extra sprite written after the run (ring frames, mirrored states); returns its [x, y, w, h]."""
    out = os.path.join(PUB, screen, f'{name}.webp')
    uix.save_rgba(out, rgb, alpha, quality=quality)
    return [int(box[0]), int(box[1]), int(rgb.shape[1]), int(rgb.shape[0])]


def ring_part(screen, name, img, box, core, ring=14, kinds=('gold', 'blue', 'red'), keep_inner=6):
    """Only the frame of a tile: its mask minus the eroded interior (the art inside stays transparent)."""
    m = frame_mask(img, box, core, ring=ring, kinds=kinds)
    inner = uix.erode(m, ring + 4 - keep_inner)
    a = cv2.GaussianBlur(cv2.subtract(m, inner), (0, 0), 0.7)
    ys, xs = np.nonzero(a > 2)
    x0, y0, x1, y1 = xs.min(), ys.min(), xs.max() + 1, ys.max() + 1
    return save_part(screen, name, img[y0:y1, x0:x1], a[y0:y1, x0:x1], (x0, y0))


def append_ts(screen, extra_sprites: dict, extra_consts: dict | None = None):
    """Add post-run sprites (rings, states) to the generated table."""
    p = os.path.join(v2x.TS_DIR, f'{screen}.ts')
    src = open(p).read()
    name = v2x.ident(screen).upper()
    head = f'export const {name}_ART = {{\n'
    add = ''.join(f'  {json.dumps(k)}: {json.dumps(v)},\n' for k, v in extra_sprites.items())
    src = src.replace(head, head + add, 1)
    for k, v in (extra_consts or {}).items():
        src += f'export const {name}_{k.upper()} = {json.dumps(v)} as const;\n'
    open(p, 'w').write(src)
