// GENERATED by tools/ui-extract/arena_select.py - do not edit by hand (re-run the script instead).

import I_bg from '../img/arenasel/bg.webp';
import I_preview from '../img/arenasel/preview.webp';
import I_tile_on from '../img/arenasel/tile_on.webp';
import I_tile from '../img/arenasel/tile.webp';
import I_locked from '../img/arenasel/locked.webp';
import I_back from '../img/arenasel/back.webp';
import I_go from '../img/arenasel/go.webp';

export interface RefSprite {
  src: string;
  x: number;
  y: number;
  w: number;
  h: number;
}

export const AS_ART = {
  "bg": { src: I_bg, x: -220, y: 0, w: 2440, h: 1125 },
  "preview": { src: I_preview, x: 358, y: 368, w: 864, h: 416 },
  "tile_on": { src: I_tile_on, x: 341, y: 751, w: 238, h: 219 },
  "tile": { src: I_tile, x: 570, y: 775, w: 214, h: 196 },
  "locked": { src: I_locked, x: 583, y: 795, w: 187, h: 159 },
  "back": { src: I_back, x: 43, y: 974, w: 440, h: 112 },
  "go": { src: I_go, x: 1412, y: 968, w: 547, h: 118 },
} satisfies Record<string, RefSprite>;

export const AS_BOXES = {
  "previewWindow": [432, 390, 1181, 740],
  "tileWindow": [13, 9, 200, 168],
  "tiles": [[357, 786, 564, 960], [570, 786, 777, 960], [784, 786, 991, 960], [997, 786, 1204, 960], [1210, 786, 1417, 960], [1424, 786, 1631, 960]],
  "title": [700, 296, 1282, 394],
  "name": [1248, 414, 1608, 462],
  "district": [1294, 476, 1504, 508],
  "desc": [1246, 520, 1610, 608],
  "labels": [1296, 626, 1388, 746],
  "values": [1438, 626, 1552, 746],
  "back_text": [250, 1006, 366, 1054],
  "go_text": [1514, 1004, 1792, 1056],
} as const;
