// GENERATED by tools/ui-extract/leaderboard.py - do not edit by hand (re-run the script instead).

import I_plate from '../img/board/plate.webp';
import I_you_row from '../img/board/you_row.webp';
import I_backdrop from '../img/board/backdrop.webp';
import I_panel from '../img/board/panel.webp';
import I_side from '../img/board/side.webp';
import I_btn_blue from '../img/board/btn_blue.webp';
import I_btn_gold from '../img/board/btn_gold.webp';

export interface RefSprite {
  src: string;
  x: number;
  y: number;
  w: number;
  h: number;
}

export const LB_ART = {
  "plate": { src: I_plate, x: 0, y: 0, w: 2000, h: 1125 },
  "you_row": { src: I_you_row, x: 412, y: 826, w: 1038, h: 64 },
  "backdrop": { src: I_backdrop, x: -420, y: -90, w: 2840, h: 1305 },
  "panel": { src: I_panel, x: 397, y: 393, w: 1067, h: 646 },
  "side": { src: I_side, x: 75, y: 324, w: 325, h: 516 },
  "btn_blue": { src: I_btn_blue, x: 58, y: 973, w: 316, h: 101 },
  "btn_gold": { src: I_btn_gold, x: 1490, y: 936, w: 462, h: 130 },
} satisfies Record<string, RefSprite>;

export const LB_BOXES = {
  "rows": [[450, 536], [544, 612], [618, 690], [696, 758], [760, 822], [826, 890], [890, 952], [954, 1016]],
  "rowX": [412, 1450],
  "avatarX": [588, 668],
  "title": [668, 288, 1420, 402],
  "tiers": [84, 333, 390, 830],
  "table": [407, 403, 1454, 1029],
  "stats": [1474, 378, 1927, 920],
  "season": [1500, 946, 1942, 1057],
  "back": [68, 983, 364, 1064],
} as const;
