// GENERATED by tools/ui-extract/char_select.py - do not edit by hand (re-run the script instead).

import I_bg from '../img/select/bg.webp';
import I_back from '../img/select/back.webp';
import I_ready from '../img/select/ready.webp';

export interface RefSprite {
  src: string;
  x: number;
  y: number;
  w: number;
  h: number;
}

export const CS_ART = {
  "bg": { src: I_bg, x: -420, y: -90, w: 2840, h: 1305 },
  "back": { src: I_back, x: 348, y: 981, w: 305, h: 94 },
  "ready": { src: I_ready, x: 1331, y: 970, w: 340, h: 112 },
} satisfies Record<string, RefSprite>;

export const CS_BOXES = {
  "p1_label": [676, 802, 796, 834],
  "p1_name": [640, 832, 890, 905],
  "p1_city": [712, 900, 838, 950],
  "p2_label": [1208, 802, 1336, 834],
  "p2_name": [1094, 832, 1418, 905],
  "p2_city": [1172, 900, 1306, 950],
  "tile_p1": [801, 441, 916, 539],
  "tile_p2": [1081, 440, 1201, 539],
  "ped_p1": [165, 300, 565, 860],
  "ped_p2": [1435, 300, 1835, 860],
  "back_text": [472, 1004, 576, 1052],
  "ready_text": [1366, 994, 1630, 1068],
  "side": 420,
  "top": 90,
} as const;
