// GENERATED by tools/ui-extract/hud.py - do not edit by hand (re-run the script instead).

import I_p1_hp from '../img/hud/p1_hp.webp';
import I_p1_pill0 from '../img/hud/p1_pill0.webp';
import I_p1_pill1 from '../img/hud/p1_pill1.webp';
import I_p1_pill2 from '../img/hud/p1_pill2.webp';
import I_p1 from '../img/hud/p1.webp';
import I_p2_hp from '../img/hud/p2_hp.webp';
import I_p2_pill0 from '../img/hud/p2_pill0.webp';
import I_p2_pill1 from '../img/hud/p2_pill1.webp';
import I_p2_pill2 from '../img/hud/p2_pill2.webp';
import I_p2 from '../img/hud/p2.webp';
import I_timer from '../img/hud/timer.webp';
import I_pause from '../img/hud/pause.webp';
import I_card0 from '../img/hud/card0.webp';
import I_card1 from '../img/hud/card1.webp';
import I_card2 from '../img/hud/card2.webp';
import I_hype_fill from '../img/hud/hype_fill.webp';
import I_hype from '../img/hud/hype.webp';
import I_info from '../img/hud/info.webp';

export interface RefSprite {
  src: string;
  x: number;
  y: number;
  w: number;
  h: number;
}

export const HUD_ART = {
  "p1_hp": { src: I_p1_hp, x: 346, y: 118, w: 526, h: 52 },
  "p1_pill0": { src: I_p1_pill0, x: 258, y: 196, w: 130, h: 32 },
  "p1_pill1": { src: I_p1_pill1, x: 464, y: 196, w: 135, h: 32 },
  "p1_pill2": { src: I_p1_pill2, x: 693, y: 196, w: 151, h: 32 },
  "p1": { src: I_p1, x: 26, y: 36, w: 858, h: 216 },
  "p2_hp": { src: I_p2_hp, x: 1136, y: 118, w: 532, h: 52 },
  "p2_pill0": { src: I_p2_pill0, x: 1232, y: 196, w: 181, h: 32 },
  "p2_pill1": { src: I_p2_pill1, x: 1446, y: 196, w: 185, h: 32 },
  "p2_pill2": { src: I_p2_pill2, x: 1672, y: 196, w: 140, h: 32 },
  "p2": { src: I_p2, x: 1116, y: 36, w: 858, h: 216 },
  "timer": { src: I_timer, x: 882, y: 48, w: 238, h: 184 },
  "pause": { src: I_pause, x: 946, y: 224, w: 108, h: 80 },
  "card0": { src: I_card0, x: 609, y: 698, w: 254, h: 294 },
  "card1": { src: I_card1, x: 872, y: 704, w: 253, h: 286 },
  "card2": { src: I_card2, x: 1132, y: 696, w: 263, h: 294 },
  "hype_fill": { src: I_hype_fill, x: 697, y: 1010, w: 568, h: 60 },
  "hype": { src: I_hype, x: 581, y: 982, w: 838, h: 112 },
  "info": { src: I_info, x: 30, y: 275, w: 532, h: 271 },
} satisfies Record<string, RefSprite>;

export const HUD_BOXES = {
  "p1_hpSpan": [346, 872],
  "p1_pill0Span": [258, 388],
  "p1_pill1Span": [464, 596],
  "p1_pill2Span": [693, 833],
  "p1_portrait": [54, 70, 185, 213],
  "p1_name": [206, 56, 432, 106],
  "p1_num": [212, 118, 318, 168],
  "p2_hpSpan": [1136, 1668],
  "p2_pill0Span": [1232, 1370],
  "p2_pill1Span": [1446, 1590],
  "p2_pill2Span": [1672, 1804],
  "p2_portrait": [1814, 68, 1958, 214],
  "p2_name": [1560, 56, 1792, 106],
  "p2_num": [1676, 118, 1790, 168],
  "timerText": [948, 128, 1054, 196],
  "card0": {"art": [630, 726, 844, 902], "cost": [608, 696, 672, 760], "name": [622, 916, 782, 968], "key": [786, 908, 846, 974]},
  "card1": {"art": [890, 726, 1104, 902], "cost": [868, 696, 932, 760], "name": [882, 916, 1042, 968], "key": [1046, 908, 1106, 974]},
  "card2": {"art": [1150, 726, 1376, 902], "cost": [1128, 696, 1192, 760], "name": [1142, 916, 1314, 968], "key": [1318, 908, 1378, 974]},
  "hypeSpan": [697, 1264],
  "hypeLabel": [1268, 1004, 1392, 1066],
  "infoText": [[60, 296, 268, 520], [296, 296, 540, 520]],
} as const;
