// GENERATED by tools/ui-extract/loading.py - do not edit by hand (re-run the script instead).

import I_bg from '../img/loading/bg.webp';
import I_track from '../img/loading/track.webp';
import I_fill from '../img/loading/fill.webp';
import I_spark from '../img/loading/spark.webp';

export interface RefSprite {
  src: string;
  x: number;
  y: number;
  w: number;
  h: number;
}

export const LD_ART = {
  "bg": { src: I_bg, x: 0, y: 0, w: 2000, h: 1125 },
  "track": { src: I_track, x: 604, y: 948, w: 794, h: 80 },
  "fill": { src: I_fill, x: 625, y: 965, w: 373, h: 50 },
  "spark": { src: I_spark, x: 938, y: 940, w: 120, h: 88 },
} satisfies Record<string, RefSprite>;

export const LD_BOXES = {
  "logo": [614, 100, 1354, 619],
  "label": [806, 893, 1166, 960],
  "channel": [630, 968, 1372, 1012],
  "spark": 998,
} as const;
