// Main menu built from the PO's master screenshot (D38): every panel, icon and frame is the extracted original
// artwork (mainMenuArt.ts, generated by tools/ui-extract/main_menu.py); all text is native and German; every
// button is a real button. Coordinates are reference pixels of the 2000x1125 master; one CSS variable (--u =
// px per reference pixel) scales the whole thing. Layout keeps the master's composition and adapts it to the
// phone in landscape: groups stick to their screen edges, grow up to 20 % on wide phones and stay inside the
// safe area (notch, home bar).
import './mainMenu.css';
import { MM_ART, MM_TEXT, type RefSprite } from './mainMenuArt';

type Art = keyof typeof MM_ART;
type Box = readonly [number, number, number, number];

export interface MainMenuModel {
  name: string;
  level: number;
  xp: number;
  xpMax: number;
  coins: number;
  gems: number;
  news: number;
  mode: { title: string; status: string; detail: string };
  pass: { level: number; xp: number; xpMax: number };
}

export type MainMenuAction =
  | 'profile'
  | 'shop'
  | 'news'
  | 'settings'
  | 'quick'
  | 'online'
  | 'friend'
  | 'ranked'
  | 'leader'
  | 'mode'
  | 'play'
  | 'pass'
  | 'fighters'
  | 'arenas'
  | 'modes'
  | 'event';

const REF_W = 2000;
const REF_H = 1125;
const de = (n: number) => Math.round(n).toLocaleString('de-DE');
const esc = (t: string) => t.replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);

// --------------------------------------------------------------------------------------------- building blocks

const pos = (x: number, y: number, w: number, h: number) => `--x:${x};--y:${y};--w:${w};--h:${h}`;

function img(id: Art, ox: number, oy: number, cls = ''): string {
  const s: RefSprite = MM_ART[id];
  return `<img class="mm-art ${cls}" alt="" draggable="false" src="${s.src}" style="${pos(s.x - ox, s.y - oy, s.w, s.h)}">`;
}

interface TextOpts {
  cls: string; // style class (mm-title, mm-sub, ...)
  fs: number; // font size in reference px
  align?: 'left' | 'center' | 'right';
  html?: string; // rich content (already escaped)
}

/** Native text in a reference box (relative to the parent sprite at ox/oy); shrinks to fit if a German word is longer. */
function text(t: string, box: Box, ox: number, oy: number, o: TextOpts): string {
  const [x0, y0, x1, y1] = box;
  const inner = o.html ?? esc(t);
  return `<span class="mm-t ${o.cls}" style="${pos(x0 - ox, y0 - oy, x1 - x0, y1 - y0)};--fs:${o.fs};justify-content:${
    o.align === 'center' ? 'center' : o.align === 'right' ? 'flex-end' : 'flex-start'
  }"><i data-t="${esc(t)}">${inner}</i></span>`;
}

/** A button whose face is one extracted sprite; children are positioned relative to that sprite. */
function button(id: Art, act: MainMenuAction, gx: number, gy: number, inner: (ox: number, oy: number) => string, label: string, cls = '', attrs = ''): string {
  const s = MM_ART[id];
  return `<button class="mm-btn ${cls}" data-act="${act}" ${attrs} aria-label="${esc(label)}" style="${pos(s.x - gx, s.y - gy, s.w, s.h)}">${img(id, s.x, s.y)}${inner(
    s.x,
    s.y,
  )}</button>`;
}

const T = MM_TEXT;
const widen = (b: readonly number[], x1: number): Box => [b[0], b[1], x1, b[3]];

// --------------------------------------------------------------------------------------------- groups

interface Group {
  id: string;
  items: Art[];
  box: Box; // union of the item sprites (reference px)
}

function group(id: string, items: Art[]): Group {
  const xs0 = items.map((i) => MM_ART[i].x);
  const ys0 = items.map((i) => MM_ART[i].y);
  const xs1 = items.map((i) => MM_ART[i].x + MM_ART[i].w);
  const ys1 = items.map((i) => MM_ART[i].y + MM_ART[i].h);
  return { id, items, box: [Math.min(...xs0), Math.min(...ys0), Math.max(...xs1), Math.max(...ys1)] };
}

const G = {
  tl: group('tl', ['player']),
  tr: group('tr', ['coins', 'gems', 'bell', 'gear']),
  logo: group('logo', ['logo']),
  left: group('left', ['quick', 'online', 'friend']),
  right: group('right', ['ranked', 'leader', 'mode', 'play']),
  bl: group('bl', ['pass']),
  bc: group('bc', ['tab_chars', 'tab_arenas', 'tab_modes', 'tab_shop']),
  br: group('br', ['event']),
};
type GroupId = keyof typeof G;

function groupHtml(g: Group, body: string): string {
  const [x0, y0, x1, y1] = g.box;
  return `<div class="mm-g" data-g="${g.id}" style="--w:${x1 - x0};--h:${y1 - y0}">${body}</div>`;
}

// --------------------------------------------------------------------------------------------- render

export function mainMenuHtml(m: MainMenuModel): string {
  const xpPct = Math.max(0, Math.min(1, m.xp / Math.max(1, m.xpMax)));
  const passPct = Math.max(0, Math.min(1, m.pass.xp / Math.max(1, m.pass.xpMax)));

  const [tlx, tly] = G.tl.box;
  const player = button(
    'player',
    'profile',
    tlx,
    tly,
    (ox, oy) =>
      `${img('avatar', ox, oy, 'mm-under')}
       ${bar('xp_fill', xpPct, 244, ox, oy)}
       ${text(m.name, widen(T.player.name, 520), ox, oy, { cls: 'mm-name', fs: 42 })}
       ${text(`Lv. ${m.level}`, widen(T.player.level, 272), ox, oy, { cls: 'mm-gold mm-lv', fs: 31 })}
       ${text(`${de(m.xp)} / ${de(m.xpMax)}`, [392, 80, 514, 106], ox, oy, { cls: 'mm-small', fs: 23, align: 'right' })}`,
    'Profil',
  );

  const [trx, try_] = G.tr.box;
  const pill = (id: 'coins' | 'gems', v: number, label: string) =>
    button(id, 'shop', trx, try_, (ox, oy) => text(de(v), widen(T[id].amount, id === 'coins' ? 1446 : 1688), ox, oy, { cls: 'mm-num', fs: 43 }), label);
  const top = `${pill('coins', m.coins, 'Münzen')}${pill('gems', m.gems, 'Diamanten')}
    ${button(
      'bell',
      'news',
      trx,
      try_,
      (ox, oy) =>
        m.news > 0
          ? `${img('badge', ox, oy, 'mm-badge')}${text(String(Math.min(9, m.news)), [1828, 23, 1864, 51], ox, oy, { cls: 'mm-badge-n', fs: 26, align: 'center' })}`
          : '',
      'Neuigkeiten',
    )}
    ${button('gear', 'settings', trx, try_, () => '', 'Einstellungen')}`;

  const L = G.left.box;
  const mode = (id: 'quick' | 'online' | 'friend' | 'ranked' | 'leader', title: string, sub: string, gx: number, gy: number) =>
    button(
      id,
      id,
      gx,
      gy,
      (ox, oy) =>
        `${text(title, widen(T[id].title, id === 'ranked' || id === 'leader' ? 1898 : 472), ox, oy, { cls: 'mm-title', fs: 60 })}
         ${text(sub, widen(T[id].sub, id === 'ranked' || id === 'leader' ? 1898 : 472), ox, oy, { cls: 'mm-sub', fs: 27 })}`,
      title,
    );
  const left = `${mode('quick', 'SCHNELLKAMPF', 'SOFORT IN DEN KAMPF', L[0], L[1])}${mode('online', 'ONLINE', 'GEGEN SPIELER IM NETZ', L[0], L[1])}${mode(
    'friend',
    'GEGEN FREUNDE',
    'FORDERE DEINE CREW',
    L[0],
    L[1],
  )}`;

  const R = G.right.box;
  const right = `${mode('ranked', 'RANGLISTE', 'KÄMPF DICH NACH OBEN', R[0], R[1])}${mode('leader', 'BESTENLISTE', 'WER IST DIE LEGENDE?', R[0], R[1])}
    ${button(
      'mode',
      'mode',
      R[0],
      R[1],
      (ox, oy) =>
        `${img('spinner', ox, oy, 'mm-spin')}
         ${text('GEWÄHLTER MODUS', widen(T.mode.label, 1700), ox, oy, { cls: 'mm-label', fs: 22 })}
         ${text(m.mode.title, widen(T.mode.name, 1740), ox, oy, { cls: 'mm-title', fs: 47 })}
         ${text(m.mode.status, widen(T.mode.status, 1750), ox, oy, { cls: 'mm-status', fs: 24 })}
         ${text(m.mode.detail, widen(T.mode.wait, 1750), ox, oy, { cls: 'mm-label mm-detail', fs: 22 })}`,
      'Gewählter Modus',
    )}
    ${button('play', 'play', R[0], R[1], (ox, oy) => text('SPIELEN', [1556, 684, 1856, 790], ox, oy, { cls: 'mm-play', fs: 122, align: 'center' }), 'Spielen', 'mm-playbtn', 'data-default')}`;

  const [blx, bly] = G.bl.box;
  const pass = button(
    'pass',
    'pass',
    blx,
    bly,
    (ox, oy) =>
      `${bar('pass_fill', passPct, 212, ox, oy)}
       ${text('BATTLE PASS', widen(T.pass.title, 384), ox, oy, { cls: 'mm-title', fs: 51 })}
       ${text(String(m.pass.level), [58, 1004, 122, 1052], ox, oy, { cls: 'mm-gold mm-shield', fs: 56, align: 'center' })}
       ${text(`${m.pass.xp} / ${m.pass.xpMax}`, [272, 1027, 366, 1058], ox, oy, {
         cls: 'mm-small',
         fs: 27,
         align: 'right',
         html: `<b class="mm-goldtxt">${de(m.pass.xp)}</b>&#8239;/&#8239;${de(m.pass.xpMax)}`,
       })}`,
    'Battle Pass',
  );

  const [bcx, bcy] = G.bc.box;
  const tab = (id: 'tab_chars' | 'tab_arenas' | 'tab_modes' | 'tab_shop', act: MainMenuAction, label: string) => {
    const s = MM_ART[id];
    const b = T[id].label;
    return button(id, act, bcx, bcy, (ox, oy) => text(label, [s.x + 14, b[1], s.x + s.w - 14, b[3]], ox, oy, { cls: 'mm-tab', fs: 32, align: 'center' }), label);
  };
  const nav = `${tab('tab_chars', 'fighters', 'KÄMPFER')}${tab('tab_arenas', 'arenas', 'ARENEN')}${tab('tab_modes', 'modes', 'MODI')}${tab('tab_shop', 'shop', 'SHOP')}`;

  const [brx, bry] = G.br.box;
  const event = button(
    'event',
    'event',
    brx,
    bry,
    (ox, oy) =>
      `${text('SONDER-EVENT', widen(T.event.title, 1800), ox, oy, { cls: 'mm-gold mm-ev', fs: 36 })}
       ${text('NUR FÜR KURZE ZEIT', [1740, 1050, 1930, 1078], ox, oy, { cls: 'mm-label', fs: 21, align: 'right' })}`,
    'Sonder-Event',
  );

  const [lgx, lgy] = G.logo.box;
  const logo = `<div class="mm-logo" style="${pos(MM_ART.logo.x - lgx, MM_ART.logo.y - lgy, MM_ART.logo.w, MM_ART.logo.h)}"><img alt="RAP BRAWL" draggable="false" src="${MM_ART.logo.src}"></div>`;

  return `<div class="mm-bg" style="background-image:url(${MM_ART.bg.src})"></div>
    <div class="mm-stage">
      ${groupHtml(G.logo, logo)}
      ${groupHtml(G.tl, player)}
      ${groupHtml(G.tr, top)}
      ${groupHtml(G.left, left)}
      ${groupHtml(G.right, right)}
      ${groupHtml(G.bl, pass)}
      ${groupHtml(G.bc, nav)}
      ${groupHtml(G.br, event)}
    </div>
    <div class="mm-toast" hidden></div>`;
}

/** Progress fill: the extracted glossy strip as a 3-slice (rounded ends kept), stretched natively to `pct` of the track. */
function bar(id: 'xp_fill' | 'pass_fill', pct: number, trackW: number, ox: number, oy: number): string {
  const s = MM_ART[id];
  if (pct <= 0) return '';
  const w = Math.max(s.h, trackW * pct);
  return `<span class="mm-fill" style="${pos(s.x - ox, s.y - oy, Math.round(w), s.h)};border-image-source:url(${s.src})"></span>`;
}

// --------------------------------------------------------------------------------------------- layout

const clamp = (v: number, a: number, b: number) => Math.max(a, Math.min(b, v));

function safeInsets(root: HTMLElement): { l: number; r: number; t: number; b: number } {
  const forced = new URLSearchParams(location.search).get('safe'); // test hook: ?safe=47 simulates a notch phone
  if (forced) {
    const v = Number(forced) || 0;
    return { l: v, r: v, t: 0, b: Math.round(v * 0.45) };
  }
  let probe = root.querySelector<HTMLElement>('.mm-safe');
  if (!probe) {
    probe = document.createElement('div');
    probe.className = 'mm-safe';
    root.appendChild(probe);
  }
  const cs = getComputedStyle(probe);
  return { l: parseFloat(cs.paddingLeft) || 0, r: parseFloat(cs.paddingRight) || 0, t: parseFloat(cs.paddingTop) || 0, b: parseFloat(cs.paddingBottom) || 0 };
}

const W_ = (g: Group) => g.box[2] - g.box[0];
const H_ = (g: Group) => g.box[3] - g.box[1];

/** Scale + place the groups for the current screen. Returns the scale (px per reference px). */
export function layoutMainMenu(root: HTMLElement): number {
  const W = root.clientWidth;
  const H = root.clientHeight;
  if (!W || !H) return 0;
  const ins = safeInsets(root);
  const uw = W - ins.l - ins.r;
  const uh = H - ins.t - ins.b;
  const base = Math.min(uh / REF_H, uw / REF_W);
  // wide phones: grow up to 20 % (more readable), limited by the bottom row and the right column
  const bottomRow = W_(G.bl) + W_(G.bc) + W_(G.br) + 2 * 14 + (G.bl.box[0] + (REF_W - G.br.box[2]));
  const rightCol = G.tr.box[1] + H_(G.tr) + 10 + H_(G.right) + 12 + Math.max(H_(G.bl), H_(G.br)) + (REF_H - G.br.box[3]);
  let f = clamp(1 + (uw / base - REF_W) / 1500, 1, 1.2);
  f = Math.min(f, uw / (base * bottomRow), uh / (base * rightCol));
  f = Math.max(f, 0.75);
  const u = base * f;
  const wu = uw / u;
  const hu = uh / u;
  root.style.setProperty('--u', `${u}px`);

  const at: Record<GroupId, [number, number, number?]> = {} as Record<GroupId, [number, number, number?]>;
  const right = (g: Group) => wu - (REF_W - g.box[2]) - W_(g);
  const bottom = (g: Group) => hu - (REF_H - g.box[3]) - H_(g);
  at.tl = [G.tl.box[0], G.tl.box[1]];
  at.tr = [right(G.tr), G.tr.box[1]];
  at.bl = [G.bl.box[0], bottom(G.bl)];
  at.br = [right(G.br), bottom(G.br)];
  const bcIdeal = wu / 2 + (G.bc.box[0] - REF_W / 2);
  at.bc = [clamp(bcIdeal, at.bl[0] + W_(G.bl) + 8, at.br[0] - 8 - W_(G.bc)), bottom(G.bc)];
  const bottomTop = Math.min(at.bl[1], at.bc[1], at.br[1]);
  at.left = [G.left.box[0], clamp(Math.min(G.left.box[1], bottomTop - 10 - H_(G.left)), at.tl[1] + H_(G.tl) + 4, Infinity)];
  at.right = [right(G.right), Math.max(at.tr[1] + H_(G.tr) + 4, Math.min(G.right.box[1], bottomTop - 10 - H_(G.right)))];
  // logo: centred like the master, nudged/shrunk to stay clear of the top bar and both columns
  const lw = W_(G.logo);
  const lMin = Math.max(at.tl[0] + W_(G.tl) + 12, at.left[0] + W_(G.left) + 12);
  const lMax = Math.min(at.tr[0] - 12, at.right[0] - 12);
  const ls = clamp((lMax - lMin) / lw, 0.6, 1);
  const lx = clamp(wu / 2 + (G.logo.box[0] - REF_W / 2) + (lw * (1 - ls)) / 2, lMin, lMax - lw * ls);
  at.logo = [lx, G.logo.box[1], ls];

  for (const id of Object.keys(G) as GroupId[]) {
    const el = root.querySelector<HTMLElement>(`[data-g="${id}"]`);
    if (!el) continue;
    const [x, y, s = 1] = at[id];
    el.style.transform = `translate(${ins.l + x * u}px, ${ins.t + y * u}px)${s !== 1 ? ` scale(${s})` : ''}`;
  }
  fitTexts(root);
  return u;
}

/** Shrink native text that is wider than its box (German words run longer than the English master). */
export function fitTexts(root: HTMLElement): void {
  root.querySelectorAll<HTMLElement>('.mm-t').forEach((el) => {
    el.style.setProperty('--fit', '1');
    const i = el.firstElementChild as HTMLElement | null;
    if (!i) return;
    const need = i.scrollWidth;
    const have = el.clientWidth;
    if (need > have && need > 0) el.style.setProperty('--fit', (have / need).toFixed(3));
  });
}

export function mountMainMenu(root: HTMLElement, onAction: (a: MainMenuAction, el: HTMLElement) => void): () => void {
  root.classList.add('mm');
  const relayout = () => layoutMainMenu(root);
  relayout();
  document.fonts?.ready.then(relayout).catch(() => undefined);
  root.querySelectorAll<HTMLImageElement>('img').forEach((im) => im.complete || im.addEventListener('load', () => fitTexts(root), { once: true }));
  const ro = new ResizeObserver(relayout);
  ro.observe(root);
  root.addEventListener('click', (e) => {
    const b = (e.target as HTMLElement).closest<HTMLElement>('[data-act]');
    if (b) onAction(b.dataset.act as MainMenuAction, b);
  });
  return () => ro.disconnect();
}

let toastTimer = 0;
export function mainMenuToast(root: HTMLElement, msg: string): void {
  const t = root.querySelector<HTMLElement>('.mm-toast');
  if (!t) return;
  t.textContent = msg;
  t.hidden = false;
  t.classList.remove('on');
  void t.offsetWidth;
  t.classList.add('on');
  clearTimeout(toastTimer);
  toastTimer = window.setTimeout(() => (t.hidden = true), 2200);
}
