// GENERATED by tools/ui-extract/main_menu.py - do not edit by hand (re-run the script instead).

import I_bg from '../img/menu/bg.webp';
import I_player from '../img/menu/player.webp';
import I_coins from '../img/menu/coins.webp';
import I_gems from '../img/menu/gems.webp';
import I_bell from '../img/menu/bell.webp';
import I_gear from '../img/menu/gear.webp';
import I_quick from '../img/menu/quick.webp';
import I_online from '../img/menu/online.webp';
import I_friend from '../img/menu/friend.webp';
import I_ranked from '../img/menu/ranked.webp';
import I_leader from '../img/menu/leader.webp';
import I_mode from '../img/menu/mode.webp';
import I_play from '../img/menu/play.webp';
import I_pass from '../img/menu/pass.webp';
import I_tab_chars from '../img/menu/tab_chars.webp';
import I_tab_arenas from '../img/menu/tab_arenas.webp';
import I_tab_modes from '../img/menu/tab_modes.webp';
import I_tab_shop from '../img/menu/tab_shop.webp';
import I_event from '../img/menu/event.webp';
import I_xp_fill from '../img/menu/xp_fill.webp';
import I_pass_fill from '../img/menu/pass_fill.webp';
import I_spinner from '../img/menu/spinner.webp';
import I_badge from '../img/menu/badge.webp';
import I_avatar from '../img/menu/avatar.webp';
import I_logo from '../img/menu/logo.webp';

export interface RefSprite {
  src: string;
  x: number;
  y: number;
  w: number;
  h: number;
}

export const MM_ART = {
  "bg": { src: I_bg, x: 0, y: 0, w: 2000, h: 1125 },
  "player": { src: I_player, x: 36, y: 10, w: 576, h: 146 },
  "coins": { src: I_coins, x: 1271, y: 20, w: 246, h: 88 },
  "gems": { src: I_gems, x: 1515, y: 19, w: 245, h: 90 },
  "bell": { src: I_bell, x: 1761, y: 14, w: 110, h: 96 },
  "gear": { src: I_gear, x: 1873, y: 18, w: 111, h: 92 },
  "quick": { src: I_quick, x: 25, y: 190, w: 509, h: 172 },
  "online": { src: I_online, x: 26, y: 350, w: 509, h: 154 },
  "friend": { src: I_friend, x: 29, y: 493, w: 506, h: 155 },
  "ranked": { src: I_ranked, x: 1466, y: 210, w: 515, h: 152 },
  "leader": { src: I_leader, x: 1465, y: 350, w: 511, h: 151 },
  "mode": { src: I_mode, x: 1464, y: 491, w: 513, h: 181 },
  "play": { src: I_play, x: 1463, y: 666, w: 511, h: 154 },
  "pass": { src: I_pass, x: 18, y: 935, w: 540, h: 190 },
  "tab_chars": { src: I_tab_chars, x: 604, y: 955, w: 226, h: 155 },
  "tab_arenas": { src: I_tab_arenas, x: 808, y: 958, w: 204, h: 150 },
  "tab_modes": { src: I_tab_modes, x: 990, y: 958, w: 206, h: 151 },
  "tab_shop": { src: I_tab_shop, x: 1174, y: 957, w: 220, h: 151 },
  "event": { src: I_event, x: 1446, y: 934, w: 539, h: 190 },
  "xp_fill": { src: I_xp_fill, x: 274, y: 78, w: 94, h: 28 },
  "pass_fill": { src: I_pass_fill, x: 156, y: 1027, w: 118, h: 33 },
  "spinner": { src: I_spinner, x: 1494, y: 587, w: 56, h: 60 },
  "badge": { src: I_badge, x: 1826, y: 20, w: 40, h: 34 },
  "avatar": { src: I_avatar, x: 46, y: 24, w: 134, h: 117 },
  "logo": { src: I_logo, x: 775, y: 12, w: 483, h: 376 },
} satisfies Record<string, RefSprite>;

export const MM_TEXT = {
  "player": {"name": [190, 30, 302, 74], "level": [190, 76, 270, 108], "xp": [422, 80, 520, 106], "slot": [[57, 26], [177, 33], [171, 139], [48, 133]]},
  "coins": {"amount": [1344, 42, 1436, 82]},
  "gems": {"amount": [1589, 42, 1650, 82]},
  "bell": {},
  "gear": {},
  "quick": {"title": [252, 240, 470, 294], "sub": [252, 295, 464, 323]},
  "online": {"title": [254, 382, 386, 432], "sub": [254, 435, 484, 462]},
  "friend": {"title": [254, 521, 440, 571], "sub": [254, 574, 472, 602]},
  "ranked": {"title": [1686, 249, 1838, 297], "sub": [1686, 298, 1874, 327]},
  "leader": {"title": [1686, 388, 1908, 434], "sub": [1686, 435, 1906, 466]},
  "mode": {"label": [1501, 511, 1643, 536], "name": [1495, 536, 1686, 577], "status": [1554, 592, 1738, 618], "wait": [1554, 621, 1708, 647]},
  "play": {},
  "pass": {"title": [154, 968, 364, 1015], "level": [66, 1004, 116, 1052], "progress": [284, 1027, 370, 1058]},
  "tab_chars": {"label": [642, 1044, 788, 1080]},
  "tab_arenas": {"label": [862, 1044, 954, 1082]},
  "tab_modes": {"label": [1048, 1046, 1130, 1080]},
  "tab_shop": {"label": [1236, 1046, 1304, 1080]},
  "event": {"title": [1598, 953, 1778, 992], "sub": [1782, 1050, 1928, 1078]},
} as const;

export const MM_LOGO_SRC = {
  "w": 1348,
  "h": 993,
} as const;
