// GENERATED by tools/ui-extract/shop.py - do not edit by hand (re-run the script instead).

import I_bg from '../img/shop/bg.webp';
import I_back from '../img/shop/back.webp';
import I_coins from '../img/shop/coins.webp';
import I_gems from '../img/shop/gems.webp';
import I_menu from '../img/shop/menu.webp';
import I_tab_skins from '../img/shop/tab_skins.webp';
import I_tab_gear from '../img/shop/tab_gear.webp';
import I_tab_emotes from '../img/shop/tab_emotes.webp';
import I_tab_currency from '../img/shop/tab_currency.webp';
import I_tab_bundles from '../img/shop/tab_bundles.webp';
import I_card_champ from '../img/shop/card_champ.webp';
import I_card_verse from '../img/shop/card_verse.webp';
import I_card_flow from '../img/shop/card_flow.webp';
import I_card_gloves from '../img/shop/card_gloves.webp';
import I_card_kicks from '../img/shop/card_kicks.webp';
import I_bundle from '../img/shop/bundle.webp';

export interface RefSprite {
  src: string;
  x: number;
  y: number;
  w: number;
  h: number;
}

export const SH_ART = {
  "bg": { src: I_bg, x: -220, y: 0, w: 2440, h: 1125 },
  "back": { src: I_back, x: 12, y: 4, w: 161, h: 105 },
  "coins": { src: I_coins, x: 1294, y: 13, w: 273, h: 84 },
  "gems": { src: I_gems, x: 1565, y: 12, w: 263, h: 85 },
  "menu": { src: I_menu, x: 1841, y: 4, w: 127, h: 106 },
  "tab_skins": { src: I_tab_skins, x: 340, y: 446, w: 278, h: 154 },
  "tab_gear": { src: I_tab_gear, x: 598, y: 445, w: 273, h: 160 },
  "tab_emotes": { src: I_tab_emotes, x: 847, y: 449, w: 266, h: 152 },
  "tab_currency": { src: I_tab_currency, x: 1098, y: 447, w: 268, h: 154 },
  "tab_bundles": { src: I_tab_bundles, x: 1341, y: 445, w: 303, h: 160 },
  "card_champ": { src: I_card_champ, x: 190, y: 611, w: 234, h: 378 },
  "card_verse": { src: I_card_verse, x: 404, y: 612, w: 220, h: 377 },
  "card_flow": { src: I_card_flow, x: 608, y: 612, w: 224, h: 378 },
  "card_gloves": { src: I_card_gloves, x: 1389, y: 612, w: 221, h: 377 },
  "card_kicks": { src: I_card_kicks, x: 1593, y: 612, w: 231, h: 377 },
  "bundle": { src: I_bundle, x: 829, y: 595, w: 568, h: 418 },
} satisfies Record<string, RefSprite>;

export const SH_BOXES = {
  "skins": [352, 456, 610, 594],
  "gear": [612, 458, 857, 592],
  "emotes": [857, 458, 1105, 592],
  "currency": [1105, 458, 1353, 592],
  "bundles": [1353, 458, 1632, 592],
  "card_champ": [200, 610, 414, 984],
  "card_verse": [412, 610, 622, 984],
  "card_flow": [618, 610, 828, 984],
  "card_gloves": [1392, 610, 1600, 984],
  "card_kicks": [1598, 610, 1814, 984],
  "labelY": [546, 590],
  "nameY": [888, 925],
  "priceY": [929, 967],
  "bundle": [834, 598, 1394, 1004],
  "bundleTitle": [896, 612, 1350, 712],
  "bundle_ribbon": [856, 620, 968, 664],
  "bundle_price": [970, 932, 1200, 990],
  "priceX": {"champ": 278, "verse": 494, "flow": 700, "gloves": 1491, "kicks": 1713},
  "coinsNum": [1368, 32, 1492, 80],
  "gemsNum": [1652, 32, 1758, 80],
} as const;
