"""A captured punch as a game move clip (S17): real timing and whole-body motion, the fist still on the sim's hitbox.

  python3 tools/mocap/strike.py <clip.bvh> <L|R> <t_start> <t_peak> <t_end> <startup> <active> <total> <out.ts> <Name>
      [--face 0.6] [--hold 0.03] [--pre 0.04]

The punch (times from tools/mocap/punches.py) is time-warped onto the move's frame data: the hand leaves the guard on
frame 0, reaches full extension on the first active frame, stays out through the active frames and is back in guard
on the last frame. Per game frame the clip stores
  - d: every joint's change since the punch started (reference-rig Euler, tools/mocap/retarget.py), added at runtime
    to the fighter's authored stance: the stance keeps its look, the body moves like the recording (hip turn, shoulder
    roll, weight transfer, head slip);
  - aim: the striking arm's upper-arm and forearm directions in the fighter frame (x = opponent, y = up, z = camera),
    so the fist goes where the capture's fist went whatever the torso does;
  - x/y: the hips' travel (step-in), faded back to zero over the recovery.
"""
from __future__ import annotations

import argparse
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from retarget import ORDER, solve  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('bvh')
    ap.add_argument('hand', choices=['L', 'R'])
    ap.add_argument('t_start', type=float)
    ap.add_argument('t_peak', type=float)
    ap.add_argument('t_end', type=float)
    ap.add_argument('startup', type=int)
    ap.add_argument('active', type=int)
    ap.add_argument('total', type=int)
    ap.add_argument('out')
    ap.add_argument('name')
    ap.add_argument('--face', type=float, default=0.6)
    ap.add_argument('--hold', type=float, default=0.03, help='capture seconds spread over the active frames')
    ap.add_argument('--pre', type=float, default=0.04, help='capture seconds before the hand leaves the guard (frame 0)')
    ap.add_argument('--mirror', action='store_true')
    a = ap.parse_args()
    w0 = a.t_start - a.pre
    E, rx, ry, CP, fps = solve(a.bvh, w0, a.t_end + 0.1, mirror=a.mirror, drift=True)
    last_act = a.startup + a.active - 1
    # game frame -> capture time (piecewise linear)
    fx = [0, a.startup, last_act, a.total]
    tx = [w0, a.t_peak, a.t_peak + a.hold, a.t_end]
    side = 'Left' if a.hand == 'L' else 'Right'

    def at(arr, t):
        u = (t - w0) * fps
        i = int(np.clip(np.floor(u), 0, len(arr) - 2))
        f = float(np.clip(u - i, 0, 1))
        return arr[i] * (1 - f) + arr[i + 1] * f

    E0 = {jn: at(E[jn], w0) for jn in ORDER}
    x0, y0 = at(rx, w0), at(ry, w0)
    keys = []
    for f in range(a.total + 1):
        t = float(np.interp(f, fx, tx))
        d = {}
        for jn in ORDER:
            if jn in (f'sh{a.hand}', f'el{a.hand}'):
                continue
            v = at(E[jn], t) - E0[jn]
            v = (v + 180) % 360 - 180
            d[jn] = v
        up = at(CP[side + 'ForeArm'], t) - at(CP[side + 'Arm'], t)
        fo = at(CP[side + 'Hand'], t) - at(CP[side + 'ForeArm'], t)
        up /= np.linalg.norm(up)
        fo /= np.linalg.norm(fo)
        # step-in kept through the hit, returned over the recovery (the sim owns the real position)
        k = np.clip((f - last_act) / max(1, a.total - last_act), 0, 1)
        back = k * k * (3 - 2 * k)
        x = (at(rx, t) - x0) * (1 - back)
        y = (at(ry, t) - y0) * (1 - back)
        keys.append((f, x, y, d, up, fo))
    nm = f'sh{a.hand}', f'el{a.hand}'
    lines = [f'// Generated by tools/mocap/strike.py from CMU mocap {os.path.basename(a.bvh)} ({a.hand} {a.t_start}-{a.t_peak}-{a.t_end} s'
             f' onto startup {a.startup}, active {a.active}, total {a.total}) - do not edit.',
             '// CMU Graphics Lab Motion Capture Database (mocap.cs.cmu.edu): free for research and commercial projects.',
             "import type { StrikeKey } from './apply';", '',
             f'export const {a.name}: StrikeKey[] = [']
    for f, x, y, d, up, fo in keys:
        ds = ', '.join(f'{jn}: [{v[0]:.1f}, {v[1]:.1f}, {v[2]:.1f}]' for jn, v in d.items())
        lines.append(f'  {{ f: {f}, x: {x:.3f}, y: {y:.3f}, aim: {{ {nm[0]}: [{up[0]:.3f}, {up[1]:.3f}, {up[2]:.3f}], {nm[1]}: [{fo[0]:.3f}, {fo[1]:.3f}, {fo[2]:.3f}], face: {a.face} }}, d: {{ {ds} }} }},')
    lines += ['];', '']
    open(a.out, 'w').write('\n'.join(lines))
    pk = keys[a.startup]
    print('wrote', a.out, len(keys), 'keys; at the first active frame: forearm dir', pk[5].round(2), 'step-in x', round(pk[1], 3),
          'hip turn', pk[3]['hips'].round(0), 'chest', pk[3]['chest'].round(0))


if __name__ == '__main__':
    main()
