// BRICK — original placeholder test fighter.
// Archetype: heavy bruiser / grappler. Producer-turned-bodyguard with a boombox.
// Slow, long reach, high damage, armor and command grabs. Prototype tuning.

import type { FighterDef, MoveDef } from '../core/defs';
import { jumpPhysics, m, mps } from '../core/math';
import { box, hit, simpleMove } from './build';

const [gravity, jumpVy] = jumpPhysics(46, 1.25);

const N = {
  L5: 'brick_5L',
  L2: 'brick_2L',
  H5: 'brick_5H',
  H2: 'brick_2H',
  H6: 'brick_6H',
  jL: 'brick_jL',
  jH: 'brick_jH',
  throw: 'brick_throw',
};
const LIGHT_CHAINS = [N.L5, N.L2, N.H5, N.H2];

const moves: MoveDef[] = [
  simpleMove(N.L5, 'normal', {
    name: 'Palm Jab',
    startup: 6,
    active: 3,
    recovery: 10,
    hit: { damage: 45, strength: 0, hitstun: 15, blockstun: 11, boxes: [box(0.25, 0.88, 1.15, 1.58)], reaction: 'high' },
    extra: { chains: LIGHT_CHAINS, specialCancel: true, hurt: [{ start: 5, end: 12, boxes: [box(0.25, 0.7, 1.2, 1.55)] }] },
  }),
  simpleMove(N.L2, 'normal', {
    name: 'Stomp',
    startup: 7,
    active: 3,
    recovery: 11,
    hit: { damage: 40, strength: 0, hitstun: 15, blockstun: 11, level: 'low', boxes: [box(0.2, 0.86, 0.0, 0.32)], reaction: 'low' },
    extra: { crouching: true, chains: LIGHT_CHAINS, specialCancel: true, hurt: [{ start: 6, end: 14, boxes: [box(0.2, 0.75, 0, 0.35)] }] },
  }),
  simpleMove(N.H5, 'normal', {
    name: 'Haymaker',
    startup: 12,
    active: 4,
    recovery: 20,
    hit: { damage: 105, strength: 2, hitstun: 22, blockstun: 17, boxes: [box(0.3, 1.12, 1.1, 1.62)], reaction: 'high' },
    extra: {
      specialCancel: true,
      velocity: [
        { frame: 7, vx: mps(1.0) },
        { frame: 14, vx: 0 },
      ],
      hurt: [{ start: 10, end: 28, boxes: [box(0.25, 0.95, 1.1, 1.6)] }],
    },
  }),
  simpleMove(N.H2, 'normal', {
    name: 'Rising Uppercut',
    startup: 11,
    active: 5,
    recovery: 24,
    hit: {
      damage: 85,
      strength: 2,
      blockstun: 15,
      boxes: [box(0.15, 0.88, 0.6, 2.15)],
      launch: { vx: 120, vy: 1500 },
      reaction: 'gut',
    },
    extra: { specialCancel: true, hurt: [{ start: 10, end: 30, boxes: [box(0.1, 0.7, 1.4, 2.1)] }] },
  }),
  simpleMove(N.H6, 'normal', {
    name: 'Elbow Drop',
    startup: 21,
    active: 4,
    recovery: 16,
    hit: { damage: 95, strength: 2, hitstun: 20, blockstun: 14, level: 'overhead', boxes: [box(0.2, 0.98, 0.8, 1.95)], reaction: 'high' },
    extra: {
      velocity: [
        { frame: 6, vx: mps(1.8) },
        { frame: 19, vx: 0 },
      ],
    },
  }),
  simpleMove(N.jL, 'normal', {
    name: 'Air Elbow',
    startup: 6,
    active: 6,
    recovery: 8,
    hit: { damage: 50, strength: 0, hitstun: 13, blockstun: 10, level: 'overhead', boxes: [box(0.05, 0.62, 0.3, 1.0)] },
    extra: { air: true, landingLag: 3 },
  }),
  simpleMove(N.jH, 'normal', {
    name: 'Big Splash',
    startup: 10,
    active: 6,
    recovery: 10,
    hit: { damage: 95, strength: 2, hitstun: 19, blockstun: 15, level: 'overhead', boxes: [box(-0.2, 0.78, -0.1, 0.62)] },
    extra: { air: true, landingLag: 5 },
  }),
  simpleMove(N.throw, 'throw', {
    name: 'Bouncer Toss',
    startup: 6,
    active: 2,
    recovery: 22,
    hit: {
      damage: 0,
      strength: 2,
      level: 'unblockable',
      boxes: [box(0.2, 0.78, 0.4, 1.6)],
      throw: { kind: 'normal', frames: 50, damageFrame: 34, damage: 135, endDx: m(1.8), anim: 'brick_throw' },
    },
  }),

  // ---- Specials (cards) ----
  {
    key: 'brick_sub',
    name: 'Subwoofer',
    kind: 'special',
    total: 46,
    hits: [],
    projectile: {
      frame: 18,
      def: {
        kind: 'wave',
        x: m(0.6),
        y: m(0.2),
        speed: mps(6),
        half: { w: m(0.28), h: m(0.2) },
        life: 80,
        hit: hit(1, 1, {
          damage: 65,
          chip: 8,
          strength: 1,
          hitstun: 22,
          blockstun: 16,
          hitstop: 8,
          level: 'low',
          boxes: [],
          meterOnHit: 0,
          meterOnBlock: 0,
        }),
      },
    },
  },
  {
    key: 'brick_dozer',
    name: 'Bulldozer',
    kind: 'special',
    total: 46,
    armor: { start: 4, end: 20, hits: 1 },
    velocity: [
      { frame: 6, vx: mps(6.5) },
      { frame: 22, vx: 0 },
    ],
    hits: [
      hit(10, 22, {
        damage: 100,
        chip: 10,
        strength: 2,
        blockstun: 18,
        knockdown: true,
        launch: { vx: 420, vy: 650 },
        boxes: [box(0.1, 0.82, 0.4, 1.75)],
        meterOnHit: 0,
        meterOnBlock: 0,
      }),
    ],
  },
  simpleMove('brick_cmd', 'special', {
    name: 'Security Check',
    startup: 8,
    active: 3,
    recovery: 30,
    hit: {
      damage: 0,
      strength: 2,
      level: 'unblockable',
      boxes: [box(0.1, 0.98, 0.2, 1.7)],
      throw: { kind: 'command', frames: 56, damageFrame: 40, damage: 210, endDx: m(1.6), anim: 'brick_cmd' },
    },
  }),
  {
    key: 'brick_drop',
    name: 'Bass Drop',
    kind: 'special',
    total: 44,
    fullInvuln: [1, 12],
    hits: [
      hit(10, 14, {
        damage: 50,
        chip: 10,
        strength: 2,
        blockstun: 18,
        knockdown: true,
        boxes: [box(-1.1, 1.1, 0.0, 1.3)],
        meterOnHit: 0,
        meterOnBlock: 0,
      }),
    ],
  },
  {
    key: 'brick_lariat',
    name: 'Heavy Rotation',
    kind: 'special',
    total: 50,
    strikeInvuln: [1, 7],
    velocity: [
      { frame: 4, vx: mps(2.4) },
      { frame: 30, vx: 0 },
    ],
    hits: [
      hit(8, 14, {
        damage: 50,
        chip: 6,
        strength: 1,
        hitstun: 24,
        blockstun: 14,
        boxes: [box(-0.9, 0.95, 0.9, 1.95)],
        meterOnHit: 0,
        meterOnBlock: 0,
      }),
      hit(20, 26, {
        damage: 60,
        chip: 6,
        strength: 2,
        blockstun: 14,
        knockdown: true,
        launch: { vx: 300, vy: 1000 },
        boxes: [box(-0.9, 0.95, 0.9, 1.95)],
        meterOnHit: 0,
        meterOnBlock: 0,
      }),
    ],
  },
  {
    key: 'brick_security',
    name: 'Security!',
    kind: 'signature',
    total: 62,
    superFlash: 36,
    fullInvuln: [1, 8],
    velocity: [
      { frame: 3, vx: mps(5) },
      { frame: 13, vx: 0 },
    ],
    hits: [
      hit(9, 13, {
        damage: 10,
        strength: 3,
        level: 'unblockable',
        boxes: [box(0, 0.9, 0.3, 1.8)],
        cinematic: 'brick_security',
        grabLike: true,
        meterOnHit: 0,
      }),
    ],
  },
];

export const BRICK: FighterDef = {
  id: 'brick',
  name: 'BRICK',
  tagline: 'Producer. Bodyguard. Wall.',
  archetype: 'Heavy Grappler',
  health: 1150,
  walkF: mps(2.5),
  walkB: mps(2.0),
  jumpSquat: 5,
  jumpVy,
  jumpVx: mps(3.0),
  gravity,
  dashF: { frames: 22, speed: mps(5.0) },
  dashB: { frames: 24, speed: mps(3.8), invuln: 6 },
  pushHalf: m(0.32),
  height: m(1.95),
  hurtStand: [box(-0.32, 0.34, 0, 1.6), box(-0.15, 0.22, 1.6, 1.97)],
  hurtCrouch: [box(-0.36, 0.38, 0, 1.15)],
  hurtAir: [box(-0.32, 0.32, 0.1, 1.7)],
  normals: { '5L': N.L5, '2L': N.L2, '5H': N.H5, '2H': N.H2, '6H': N.H6, jL: N.jL, jH: N.jH, throw: N.throw },
  moves: Object.fromEntries(moves.map((mv) => [mv.key, mv])),
  cards: [
    {
      id: 'brick_sub',
      name: 'Subwoofer',
      category: 'zoning',
      cost: 100,
      move: 'brick_sub',
      role: 'Low ground wave',
      description: 'Slam the boombox. A bass wave rolls along the floor — crouch-block it or jump.',
    },
    {
      id: 'brick_dozer',
      name: 'Bulldozer',
      category: 'offense',
      cost: 100,
      move: 'brick_dozer',
      role: 'Armored charge',
      description: 'Shoulder charge that eats one hit and keeps coming. Throws beat it. Unsafe if blocked.',
    },
    {
      id: 'brick_cmd',
      name: 'Security Check',
      category: 'grapple',
      cost: 200,
      move: 'brick_cmd',
      role: 'Unblockable command grab',
      description: 'Pat-down, then slam. Cannot be blocked or teched — jump or hit him first. Huge whiff recovery.',
    },
    {
      id: 'brick_drop',
      name: 'Bass Drop',
      category: 'counter',
      cost: 100,
      move: 'brick_drop',
      role: 'Invulnerable reversal',
      description: 'Stomp the drop. Fully invulnerable start, hits both sides. Your get-off-me button.',
    },
    {
      id: 'brick_lariat',
      name: 'Heavy Rotation',
      category: 'utility',
      cost: 100,
      move: 'brick_lariat',
      role: 'Anti-air spin',
      description: 'Spinning clothesline that covers both sides and the air above. Lows go under it.',
    },
    {
      id: 'brick_security',
      name: 'Security!',
      category: 'signature',
      cost: 300,
      move: 'brick_security',
      role: 'Cinematic grab super',
      description: 'Call in the crew. Unblockable lunge — on contact, security holds them while BRICK drops the hammer.',
    },
  ],
  cinematics: {
    brick_security: {
      id: 'brick_security',
      frames: 168,
      startDx: m(0.9),
      hits: [
        { frame: 56, damage: 30, strength: 1 },
        { frame: 70, damage: 30, strength: 1 },
        { frame: 122, damage: 200, strength: 3 },
      ],
      endDx: m(2.3),
    },
  },
  defaultLoadout: ['brick_sub', 'brick_dozer', 'brick_security'],
};
