// VOLT — original placeholder test fighter.
// Archetype: battle-rap rushdown. Fast, light, short reach, strong mobility.
// Prop: wireless microphone. All values are prototype tuning.

import type { FighterDef, MoveDef } from '../core/defs';
import { jumpPhysics, m, mps } from '../core/math';
import { box, hit, simpleMove } from './build';

const [gravity, jumpVy] = jumpPhysics(40, 1.5);
const [diveG, diveVy] = jumpPhysics(34, 1.6);

const N = {
  L5: 'volt_5L',
  L2: 'volt_2L',
  H5: 'volt_5H',
  H2: 'volt_2H',
  H6: 'volt_6H',
  jL: 'volt_jL',
  jH: 'volt_jH',
  throw: 'volt_throw',
};
const LIGHT_CHAINS = [N.L5, N.L2, N.H5, N.H2];

const moves: MoveDef[] = [
  simpleMove(N.L5, 'normal', {
    name: 'Jab',
    startup: 5,
    active: 2,
    recovery: 8,
    hit: { damage: 40, strength: 0, hitstun: 14, blockstun: 11, boxes: [box(0.2, 0.78, 1.18, 1.52)], reaction: 'high' },
    extra: { chains: LIGHT_CHAINS, specialCancel: true, hurt: [{ start: 4, end: 10, boxes: [box(0.2, 0.6, 1.25, 1.5)] }] },
  }),
  simpleMove(N.L2, 'normal', {
    name: 'Shin Kick',
    startup: 6,
    active: 2,
    recovery: 9,
    hit: { damage: 34, strength: 0, hitstun: 14, blockstun: 11, level: 'low', boxes: [box(0.15, 0.82, 0.0, 0.35)], reaction: 'low' },
    extra: { crouching: true, chains: LIGHT_CHAINS, specialCancel: true, hurt: [{ start: 5, end: 12, boxes: [box(0.2, 0.7, 0.0, 0.3)] }] },
  }),
  simpleMove(N.H5, 'normal', {
    name: 'Cross',
    startup: 9,
    active: 3,
    recovery: 16,
    hit: { damage: 82, strength: 2, hitstun: 20, blockstun: 15, boxes: [box(0.25, 0.98, 1.12, 1.52)], reaction: 'high' },
    extra: {
      specialCancel: true,
      velocity: [
        { frame: 5, vx: mps(1.4) },
        { frame: 12, vx: 0 },
      ],
      hurt: [{ start: 8, end: 20, boxes: [box(0.2, 0.8, 1.15, 1.5)] }],
    },
  }),
  simpleMove(N.H2, 'normal', {
    name: 'Sweep',
    startup: 10,
    active: 3,
    recovery: 21,
    hit: { damage: 76, strength: 2, blockstun: 14, level: 'low', knockdown: true, boxes: [box(0.2, 1.08, 0.0, 0.3)], reaction: 'low' },
    extra: { crouching: true, specialCancel: true, hurt: [{ start: 9, end: 26, boxes: [box(0.2, 0.95, 0.0, 0.3)] }] },
  }),
  simpleMove(N.H6, 'normal', {
    name: 'Hammer Drop',
    startup: 19,
    active: 3,
    recovery: 14,
    hit: { damage: 76, strength: 2, hitstun: 19, blockstun: 13, level: 'overhead', boxes: [box(0.15, 0.88, 0.9, 1.75)], reaction: 'high' },
    extra: {
      velocity: [
        { frame: 5, vx: mps(2.0) },
        { frame: 17, vx: 0 },
      ],
    },
  }),
  simpleMove(N.jL, 'normal', {
    name: 'Air Knee',
    startup: 5,
    active: 7,
    recovery: 6,
    hit: { damage: 45, strength: 0, hitstun: 13, blockstun: 10, level: 'overhead', boxes: [box(0.05, 0.52, 0.25, 0.95)] },
    extra: { air: true, landingLag: 3 },
  }),
  simpleMove(N.jH, 'normal', {
    name: 'Air Hammer',
    startup: 8,
    active: 4,
    recovery: 10,
    hit: { damage: 78, strength: 2, hitstun: 18, blockstun: 14, level: 'overhead', boxes: [box(-0.12, 0.72, -0.08, 0.7)] },
    extra: { air: true, landingLag: 4 },
  }),
  simpleMove(N.throw, 'throw', {
    name: 'Headlock Toss',
    startup: 5,
    active: 2,
    recovery: 20,
    hit: {
      damage: 0,
      strength: 2,
      level: 'unblockable',
      boxes: [box(0.2, 0.66, 0.4, 1.5)],
      throw: { kind: 'normal', frames: 44, damageFrame: 30, damage: 110, endDx: m(1.6), anim: 'volt_throw' },
    },
  }),

  // ---- Specials (cards) ----
  {
    key: 'volt_mic',
    name: 'Mic Check',
    kind: 'special',
    total: 40,
    hits: [],
    projectile: {
      frame: 14,
      def: {
        kind: 'mic',
        x: m(0.6),
        y: m(1.35),
        speed: mps(9),
        half: { w: m(0.16), h: m(0.13) },
        life: 64,
        returnAfter: 24,
        hit: hit(1, 1, {
          damage: 55,
          chip: 8,
          strength: 1,
          hitstun: 22,
          blockstun: 16,
          hitstop: 8,
          boxes: [],
          meterOnHit: 0,
          meterOnBlock: 0,
        }),
      },
    },
  },
  {
    key: 'volt_dive',
    name: 'Stage Dive',
    kind: 'special',
    total: 60,
    endOnLand: true,
    landingLag: 14,
    gravity: diveG,
    velocity: [{ frame: 6, vx: mps(4.6), vy: diveVy }],
    hits: [
      hit(20, 50, {
        damage: 90,
        chip: 8,
        strength: 2,
        blockstun: 14,
        level: 'overhead',
        knockdown: true,
        boxes: [box(-0.25, 0.65, -0.1, 0.7)],
        meterOnHit: 0,
        meterOnBlock: 0,
      }),
    ],
  },
  {
    key: 'volt_rush',
    name: 'Freestyle Rush',
    kind: 'special',
    total: 34,
    velocity: [
      { frame: 3, vx: mps(7) },
      { frame: 12, vx: 0 },
    ],
    hits: [
      hit(8, 11, {
        damage: 40,
        chip: 10,
        strength: 1,
        hitstun: 30,
        blockstun: 18,
        hitstop: 8,
        boxes: [box(0.1, 0.82, 0.9, 1.6)],
        followup: 'volt_rush_fu',
        meterOnHit: 0,
        meterOnBlock: 0,
      }),
    ],
  },
  {
    key: 'volt_rush_fu',
    name: 'Freestyle Rush (combo)',
    kind: 'special',
    total: 56,
    velocity: [
      { frame: 1, vx: mps(0.9) },
      { frame: 40, vx: 0 },
    ],
    hits: [
      hit(6, 6, { damage: 34, strength: 1, hitstun: 30, hitstop: 6, boxes: [box(0, 0.95, 0.8, 1.65)], pushHit: 200, meterOnHit: 0 }),
      hit(14, 14, { damage: 34, strength: 1, hitstun: 30, hitstop: 6, boxes: [box(0, 0.95, 0.8, 1.65)], pushHit: 200, meterOnHit: 0 }),
      hit(22, 22, { damage: 40, strength: 1, hitstun: 30, hitstop: 7, boxes: [box(0, 0.95, 0.8, 1.65)], pushHit: 200, meterOnHit: 0 }),
      hit(32, 33, {
        damage: 60,
        strength: 2,
        hitstop: 14,
        boxes: [box(0, 1.0, 0.6, 1.9)],
        launch: { vx: 260, vy: 1100 },
        meterOnHit: 0,
      }),
    ],
  },
  {
    key: 'volt_counter',
    name: 'Punchline',
    kind: 'special',
    total: 44,
    hits: [],
    counter: { start: 4, end: 26, followup: 'volt_counter_fu', catchLow: false, catchProjectile: false },
  },
  {
    key: 'volt_counter_fu',
    name: 'Punchline (strike)',
    kind: 'special',
    total: 32,
    fullInvuln: [1, 14],
    hits: [
      hit(5, 7, {
        damage: 110,
        strength: 3,
        hitstop: 16,
        knockdown: true,
        launch: { vx: 320, vy: 900 },
        boxes: [box(-0.2, 1.15, 0.5, 1.8)],
        meterOnHit: 0,
      }),
    ],
  },
  {
    key: 'volt_hype',
    name: 'Ad-Lib',
    kind: 'special',
    total: 70,
    hits: [],
    meterGain: { frame: 40, amount: 75 },
  },
  {
    key: 'volt_headliner',
    name: 'Headliner',
    kind: 'signature',
    total: 60,
    superFlash: 36,
    strikeInvuln: [1, 12],
    velocity: [
      { frame: 2, vx: mps(9) },
      { frame: 15, vx: 0 },
    ],
    hits: [
      hit(9, 14, {
        damage: 40,
        chip: 30,
        strength: 3,
        blockstun: 22,
        boxes: [box(0, 0.95, 0.5, 1.75)],
        cinematic: 'volt_headliner',
        meterOnHit: 0,
        meterOnBlock: 0,
      }),
    ],
  },
];

export const VOLT: FighterDef = {
  id: 'volt',
  name: 'VOLT',
  tagline: 'Battle-rap rushdown. Never lets you breathe.',
  archetype: 'Rushdown',
  health: 1000,
  meterGainPct: 130,
  walkF: mps(3.6),
  walkB: mps(2.9),
  jumpSquat: 4,
  jumpVy,
  jumpVx: mps(3.3),
  gravity,
  dashF: { frames: 16, speed: mps(6.2) },
  dashB: { frames: 20, speed: mps(4.8), invuln: 7 },
  pushHalf: m(0.24),
  height: m(1.78),
  hurtStand: [box(-0.24, 0.26, 0, 1.45), box(-0.12, 0.2, 1.45, 1.8)],
  hurtCrouch: [box(-0.28, 0.3, 0, 1.05)],
  hurtAir: [box(-0.25, 0.25, 0.1, 1.6)],
  normals: { '5L': N.L5, '2L': N.L2, '5H': N.H5, '2H': N.H2, '6H': N.H6, jL: N.jL, jH: N.jH, throw: N.throw },
  moves: Object.fromEntries(moves.map((mv) => [mv.key, mv])),
  cards: [
    {
      id: 'volt_mic',
      name: 'Mic Check',
      category: 'zoning',
      cost: 100,
      move: 'volt_mic',
      role: 'Boomerang projectile',
      description: 'Sling the mic across the stage. It flies out and swings back on the cable — watch your back.',
    },
    {
      id: 'volt_dive',
      name: 'Stage Dive',
      category: 'mobility',
      cost: 100,
      move: 'volt_dive',
      role: 'Overhead leap, can cross up',
      description: 'Leap off the stage monitors and crash down. Must be blocked standing. Knocks down.',
    },
    {
      id: 'volt_rush',
      name: 'Freestyle Rush',
      category: 'offense',
      cost: 200,
      move: 'volt_rush',
      role: 'Combo ender, rush flurry',
      description: 'Dash in with a jab. If it connects, VOLT goes off: a five-hit freestyle that launches. Unsafe if blocked.',
    },
    {
      id: 'volt_counter',
      name: 'Punchline',
      category: 'counter',
      cost: 100,
      move: 'volt_counter',
      role: 'Counter stance vs strikes',
      description: 'Bait them in. Catches standing and air strikes and answers with a knockout punchline. Lows and throws beat it.',
    },
    {
      id: 'volt_hype',
      name: 'Ad-Lib',
      category: 'utility',
      cost: 0,
      move: 'volt_hype',
      role: 'Builds meter, very punishable',
      description: 'Hype the crowd mid-fight. Gains most of a Hype bar — if they let you finish.',
    },
    {
      id: 'volt_headliner',
      name: 'Headliner',
      category: 'signature',
      cost: 300,
      move: 'volt_headliner',
      role: 'Cinematic super, invulnerable start',
      description: 'The main event. Invulnerable lunge — on hit, VOLT takes the stage for a full headline set.',
    },
  ],
  cinematics: {
    volt_headliner: {
      id: 'volt_headliner',
      frames: 156,
      startDx: m(0.85),
      hits: [
        { frame: 18, damage: 35, strength: 1 },
        { frame: 26, damage: 35, strength: 1 },
        { frame: 34, damage: 40, strength: 1 },
        { frame: 72, damage: 60, strength: 2 },
        { frame: 116, damage: 140, strength: 3 },
      ],
      endDx: m(2.0),
    },
  },
  defaultLoadout: ['volt_mic', 'volt_rush', 'volt_headliner'],
};
