// GENERATED by tools/ui-extract/v2_arena.py - do not edit by hand (re-run the script instead).
// Boxes are [x, y, w, h] in reference px of the 1672x941 master; files live in public/assets/ui2/.

export const ARENA_DIR = 'assets/ui2/arena/';
export const ARENA_SIZE = [1672, 941] as const;
export const ARENA_PLATE = {"l": [0, 0, 0, 0], "c": [0, 0, 0, 0], "r": [0, 0, 0, 0]} as const;
export const ARENA_ART = {
  "back": [9, 7, 103, 93],
  "title": [100, 0, 500, 110],
  "coin": [952, 7, 62, 62],
  "gem": [1139, 9, 65, 62],
  "bolt": [1323, 10, 50, 64],
  "plus1": [1082, 9, 54, 58],
  "plus2": [1267, 11, 53, 54],
  "plus3": [1443, 11, 54, 55],
  "mail": [1507, 16, 60, 53],
  "gear": [1587, 8, 69, 69],
  "trait1": [1219, 368, 139, 126],
  "trait2": [1367, 368, 139, 122],
  "trait3": [1514, 368, 139, 122],
  "button": [1203, 498, 459, 129],
  "arrow_l": [0, 707, 51, 98],
  "arrow_r": [1621, 714, 51, 85],
  "card_sel": [45, 615, 342, 312],
  "card": [366, 617, 329, 307],
  "badge": [1540, 2, 40, 36],
} as const;
export const ARENA_TEXT = {
  "title": {"label": [126, 18, 522, 86]},
  "trait1": {"icon": [1250, 382, 1330, 440], "label": [1234, 440, 1344, 484]},
  "trait2": {"icon": [1398, 382, 1478, 440], "label": [1382, 440, 1492, 484]},
  "trait3": {"icon": [1544, 382, 1624, 440], "label": [1528, 440, 1640, 484]},
  "button": {"label": [1296, 520, 1600, 598]},
} as const;
export const ARENA_LIGHTS: [number, number, number, [number, number, number]][] = [];
export const ARENA_CARDS = [[61, 631, 371, 911], [382, 633, 679, 908], [692, 633, 988, 908], [1000, 633, 1295, 908], [1305, 633, 1608, 908]] as const;
